[package]
name = "tsp"
version = "0.1.0"
authors = ["Amedee d'Aboville <amedee.daboville@gmail.com>"]
edition = "2018"

[dependencies]
noisy_float = "0.1.10"
regex = "1.1.6"
nom = "4.2.3"
strum = "0.15.0"
strum_macros = "0.15.0"